// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: getpwbyemail.sql

package database

import (
	"context"
)

const getPwByEmail = `-- name: GetPwByEmail :one
SELECT id, created_at, updated_at, email, hashed_password FROM users WHERE email = $1
`

func (q *Queries) GetPwByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getPwByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
