// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: newrefreshtoken.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const newRToken = `-- name: NewRToken :one
INSERT INTO refresh_tokens (token, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type NewRTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) NewRToken(ctx context.Context, arg NewRTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, newRToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
