// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: revoketoken.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const revokeRToken = `-- name: RevokeRToken :exec
UPDATE refresh_tokens
SET revoked_at = $2, updated_at = $3
WHERE token = $1
`

type RevokeRTokenParams struct {
	Token     string
	RevokedAt sql.NullTime
	UpdatedAt time.Time
}

func (q *Queries) RevokeRToken(ctx context.Context, arg RevokeRTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeRToken, arg.Token, arg.RevokedAt, arg.UpdatedAt)
	return err
}
